ДЗ module2-task1: разметка всех страниц по БЭМ
htmlacademy-adaptive/2166307-cat-energy-29 pull request #2
Opened 2023-09-05 13:08 UTC by AndrewPlatonov888

ДЗ module2-task1: разметка всех страниц по БЭМ
Доброго дня прошу проверить
ps^ надеюсь успеть защититься..

2023-09-06 06:03 UTC, Kartaviy-arteom requested changes

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +<body class="page__body">
это не по бэму, так как блока page нет

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <p class="card__description">Cat Energy PRO <br>500 г</p>
посмотри тз https://up.htmlacademy.ru/adaptive/29/project/cat-energy#cat-energy-6-1

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <button class="card__button button" type="button">Заказать</button>
заказать будет ссылкой, в тз тут https://up.htmlacademy.ru/adaptive/29/project/cat-energy#cat-energy-6-2

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +          <button class="extention__button button" type="button">Показать все</button>
это тоже ссылка. и этот див лучше оставить в списке, так у тебя будет гораздо меньше проблем со стилями

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <button class="offer__button button" type="button">Заказать</button>
ссылка

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +      </div>
промоакцию обернуть в ссылку

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +        </p>
лучше один параграф, а город обернуть внутри в спан

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +        <p class="logo__text"><b>Cat</b> energy</p>
тут будет картинка, логотипы не нужно вставлять текстом, да и в макете это svg

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/catalog.html
> +        <img class="copyright__image" src="img/fat_cat.png" width="27" height="34" alt="Логотип HTML Academy.">
логотип внутри ссылки

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/form.html
> +    <form class="form" action="https://echo.htmlacademy.ru/" method="post" id="request_form">
внутри формы бэм исправить

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/form.html
> +<body class="page__body">
тут так же как в каталоге, ошибка в БЭМ

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/index.html
> +        <button class="program__button button" type="button">Подобрать программу</button>
ссылка

2023-09-06 06:03 UTC, Kartaviy-arteom commented on source/index.html
> +        <ul class="benefits__list">
ol

2023-09-07 07:14 UTC, AndrewPlatonov888 commented on source/catalog.html
> +        </p>
сделал.

2023-09-07 07:20 UTC, AndrewPlatonov888 commented on source/catalog.html
> +<body class="page__body">
сделал <html class="page">

2023-09-07 07:21 UTC, AndrewPlatonov888 commented on source/form.html
> +<body class="page__body">
сделал <html class="page">

2023-09-07 07:28 UTC, AndrewPlatonov888 commented on source/catalog.html
> +<body class="page__body">
исправил

2023-09-07 07:29 UTC, AndrewPlatonov888 commented on source/form.html
> +<body class="page__body">
исправил

2023-09-07 07:35 UTC, AndrewPlatonov888 commented on source/catalog.html
> +            <p class="card__description">Cat Energy PRO <br>500 г</p>
изображения и названия товара - все убрал

2023-09-07 07:38 UTC, AndrewPlatonov888 commented on source/catalog.html
> +            <button class="card__button button" type="button">Заказать</button>
поправил,
тз забыл прочитать..

2023-09-07 07:41 UTC, AndrewPlatonov888 commented on source/catalog.html
> +          <button class="extention__button button" type="button">Показать все</button>
да, тоже подумывал на таким вариантом,
поправил

2023-09-07 07:43 UTC, AndrewPlatonov888 commented on source/catalog.html
> +            <button class="offer__button button" type="button">Заказать</button>
готово

2023-09-07 07:55 UTC, AndrewPlatonov888 commented on source/catalog.html
> +        <img class="copyright__image" src="img/fat_cat.png" width="27" height="34" alt="Логотип HTML Academy.">
исправил..

2023-09-07 09:00 UTC, AndrewPlatonov888 commented on source/index.html
> +        <button class="program__button button" type="button">Подобрать программу</button>
поправил

2023-09-07 09:02 UTC, AndrewPlatonov888 commented on source/index.html
> +        <ul class="benefits__list">
переправил на <ol>

2023-09-07 09:02 UTC, AndrewPlatonov888 commented on source/index.html
> +        <ul class="benefits__list">
ol

2023-09-07 09:04 UTC, AndrewPlatonov888 commented on source/catalog.html
> +      </div>
готово, обернул

2023-09-07 09:12 UTC, AndrewPlatonov888 commented on source/catalog.html
> +        <p class="logo__text"><b>Cat</b> energy</p>
что-то я много простых вещей забыл после погружения в js

2023-09-08 11:48 UTC, merged