ДЗ: module3-task1 - ВСЕ, кроме блока 'каталог' и 'форма'
htmlacademy-adaptive/2166307-cat-energy-29 pull request #3
Opened 2023-09-11 10:56 UTC by AndrewPlatonov888

Привет!
решил уже открыть пул реквест, чтобы ты взглянул на то, что уже есть и может быть какие то общие или конкретные замечания высказал.
Здесь полностью сверстана главная страница, шапка/футер/карта из нее переиспользуються на др страницах.
Остался блок-каталог и блок-форма. Постараюсь сегодня вечером доделать.
Жду замечаний!

2023-09-12 05:53 UTC, Kartaviy-arteom requested changes

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/img/nutrient_icon.svg
по-хорошему ты тут должен использовать оди подход в наименовании файлов

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/sass/blocks/benefits.scss
> +
это вынести в файл с миксинами

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/sass/blocks/benefits.scss
> +  font-family: "Oswald", sans-serif;
привести в соответствие с критерием https://up.htmlacademy.ru/adaptive/29/criteries#b10

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/sass/blocks/compare-slider.scss
> +.example__slider-wrapper {
это не должно быть в этом блоке

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/sass/style.scss
> +}
это вынести в файл fonts

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/sass/style.scss
> +
это в common или global

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/index.html
> +            <input class="compare-slider__input" type="range" min="0" max="87.5" value="44" step="0.25">
label

2023-09-12 05:53 UTC, Kartaviy-arteom commented on source/index.html
> +              <div class="compare-slider__divisor"></div>
изображения контентные и должны быть в разметке

2023-09-17 16:23 UTC, AndrewPlatonov888 commented on source/img/nutrient_icon.svg
ок привел все к единому знаменателю

2023-09-17 16:24 UTC, AndrewPlatonov888 commented on source/sass/blocks/benefits.scss
> +
все миксины вынес в отдельный файл

2023-09-17 16:35 UTC, AndrewPlatonov888 commented on source/sass/blocks/benefits.scss
> +  font-family: "Oswald", sans-serif;
все понял, добавил Тахому - безопасный шрифт без засечек

2023-09-17 16:39 UTC, AndrewPlatonov888 commented on source/sass/blocks/compare-slider.scss
> +.example__slider-wrapper {
похоже лишняя обертка, 
убрал

2023-09-17 16:39 UTC, AndrewPlatonov888 commented on source/sass/style.scss
> +}
вынес

2023-09-17 16:40 UTC, AndrewPlatonov888 commented on source/sass/style.scss
> +
сделано

2023-09-17 16:43 UTC, AndrewPlatonov888 commented on source/index.html
> +            <input class="compare-slider__input" type="range" min="0" max="87.5" value="44" step="0.25">
добавил label

2023-09-17 18:34 UTC, AndrewPlatonov888 commented on source/index.html
> +              <div class="compare-slider__divisor"></div>
немного все поломалось,
но переделал.
стало лучше: слайд не трясется

2023-09-18 11:26 UTC, merged